Feature/admin
LiorGnieslawMoveo/Epicure-Admin pull request #1
Opened 2024-04-01 13:47 UTC by LiorGnieslawMoveo

2024-04-01 14:16 UTC, Karina-Moveo requested changes

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table-datasource.ts
> +    super();
Do you need the super here?

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table-datasource.ts
> +        // case 'id': return compare(+a.id, +b.id, isAsc);
Remove comment

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table-datasource.ts
> +    if (!this.sort || !this.sort.active || this.sort.direction === '') {
Try this instead:
if (!this.sort?.active || this.sort?.direction === '') 

Read into "optional chaining" on google

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table.component.ts
> +  displayedColumns = ['id', 'name', 'description', 'restaurants', 'chefOfTheWeek', 'deleted'];
Move to data file

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/dishes-table/dishes-table-datasource.ts
> +function compare(a: string | number, b: string | number, isAsc: boolean): number {
You are repeating code, create a general use functions file

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table.component.html
> +    </ng-container>
You are repeating sections 

try using ngFor and use pre set data

something like this:
<ng-container *ngFor=data in allData>
   <ng-container matColumnDef="{{data.column}}">
      <th mat-header-cell *matHeaderCellDef mat-sort-header>data.text</th>
      <td mat-cell *matCellDef="let row">{{data.row.deleted}}</td>
    </ng-container>
</ng-container>

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/dishes-table/dishes-table.component.ts
> +  displayedColumns = ['id', 'title', 'description', 'price', 'deleted', 'iconMeaning', 'restaurant'];
Same

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/dishes-table/dishes-table.component.ts
> +    console.log(this.table.dataSource)
Remove console

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/restaurants-table/restaurants-table-datasource.ts
> +function compare(a: string | number, b: string | number, isAsc: boolean): number {
You are repeating this datasoure and writing duplicate code

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/components/restaurants-table/restaurants-table.component.html
> +  </table>
same

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/constants/chefExampleData.ts
> +// ];
Remove comments

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/interfaces/data.interface.ts
> +    dishes: string[] //IDish[]
Remove comments

2024-04-01 14:16 UTC, Karina-Moveo commented on src/app/services/chef.service.ts
> +    private apiUrl = 'http://localhost:4000/api/chefs';
use env

2024-04-01 14:38 UTC, LiorGnieslawMoveo commented on src/app/components/chefs-table/chefs-table-datasource.ts
> +    super();
because it extends datasource

2024-04-02 05:54 UTC, Karina-Moveo commented on src/app/shared/generic-table-datasource.ts
> +                // case 'title': return compare(a.title, b.title, isAsc);
Remove comment

2024-04-02 09:41 UTC, Karina-Moveo requested changes

2024-04-02 09:41 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table.component.html
> +        <select *ngIf="row.isEditing" [(ngModel)]="row.restaurants[0].title">
Don't use static array [0]

2024-04-02 09:41 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table.component.ts
> +      console.log(row)
Remove log

2024-04-02 09:41 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table.component.ts
> +      row.isEditing = !row.isEditing;
you can remove the else here and put the code
 row.isEditing = !row.isEditing;
 
 out of the else (remove it from the if also)

2024-04-02 09:42 UTC, Karina-Moveo requested changes

2024-04-02 09:42 UTC, Karina-Moveo commented on src/app/components/dishes-table/dishes-table.component.html
> +      <!-- <td mat-cell *matCellDef="let row">{{row.iconMeaning}}</td> -->
remove comment

2024-04-02 12:26 UTC, Karina-Moveo approved these changes

2024-04-03 06:00 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table.component.ts
> +      { label: 'Specialty', type: 'text', placeholder: 'Enter chef specialty' },
Static data should be in a different file

2024-04-03 06:01 UTC, Karina-Moveo commented on src/app/components/chefs-table/chefs-table.component.ts
> +    console.log(this.modalData)
Remove logs

2024-04-03 06:02 UTC, Karina-Moveo commented on src/app/components/restaurants-table/restaurants-table.component.html
> +          <option value="5">5</option>
can you maybe do an ngfor?

2024-04-03 06:05 UTC, Karina-Moveo commented on src/app/shared/generic-table-datasource.ts
> +    }
You can clear this function a little
1. don't use return so many times, instead use a variable (let) 
2. multiply by (isAsc ? 1 : -1); only once at the end 
3. You have 2 cases which are the same, clear them into one

2024-04-08 13:30 UTC, Karina-Moveo requested changes

2024-04-08 13:30 UTC, Karina-Moveo commented on src/app/components/restaurants-table/restaurants-table.component.ts
> +      chef: restaurantData.formFields[3].value,
can this be done in a loop maybe?

2024-04-08 13:30 UTC, Karina-Moveo commented on src/app/components/generic-modal/generic-modal.component.ts
> +      this.chefs = chefs;
A generic modal shouldn't know his objects, if we used this modal in a very big project it would become inefficient.
Try using props for this

2024-04-09 08:38 UTC, Karina-Moveo approved these changes

2024-04-09 10:37 UTC, Karina-Moveo approved these changes

2024-04-09 13:48 UTC, merged